### ISSUE TITLE
Stopped Working

### ISSUE THREAD

**Issue by efortenberry** [jereze/alfred-salesforce#8]
Not sure what happened, but this Alfred workflow to search Salesforce randomly stopped working.  I'm using the latest version (v0.0.4).  

Alfred 4.6.3
MacOS Monterey 12.3

This workflow is incredible, so I hope it can be updated or fixed to work again.  If there's any way I can help troubleshoot this to get it working again I'm happy to help!

**Comment by efortenberry** [comment]
I confirmed on my coworker's machine who is still on MacOS Monterey 12.1 and the latest Alfred 4.6.3 version that it does still work.  So it must be related to the MacOS Monterey 12.3 version.

**Comment by efortenberry** [comment]
Seems like it has something to do with OSX 12.3 where Apple removed the bundled Python 2 interpreter

**Comment by jereze** [comment]
I'll have a look at it in the coming days

**Comment by pascalinger** [comment]
Great news! Thanks for maintaining this script! Really helpful in my day-to-day.

**Comment by donovanwatts** [comment]
was hoping this would work but doesn't work for me either. monterey 12.3.1.

**Comment by jereze** [comment]
Hi everyone,

I've just released a new version that migrates the workflow from Python 2 to Python 3. It was broken since macOS Monterey 12.3 when Apple removed Python 2 from the pre-installed scripting languages. Python 3 is not included by default on macOS, but it is easy to install with Xcode command line tools provided by Apple. You can find instructions [here](https://macpaw.com/how-to/install-command-line-tools).

On my side, it works well with Alfred 5.0.1 on macOS Monterey (12.5.1). Should work from Alfred 4.

Ping @efortenberry @mikemajara @ktal90 @miguelalcalde @pascalinger @donovanwatts
